In [3]:
import matplotlib.pyplot as plt
from IPython.display import display, Markdown, Latex
import numpy as np
import json
import pandas as pd
from scipy import stats
import os

#with open('transfer_experiment.json', 'r') as fp:
#    data = json.load(fp)
    
def load_data(experiments):
    data = { 'results' : {} }
    for item in experiments:
        experiment_title = item['id'] + '_' + item['source'] + '_' + item['target']
        if os.path.isfile('experiments/' + experiment_title + '/' + experiment_title + '.json'):
            with open('experiments/' + experiment_title + '/' + experiment_title + '.json', 'r') as fp:
                results = json.load(fp)
                data['results'][experiment_title] = results
    return data

def load_data_old(experiments):
    data = { 'results' : {} }
    for item in experiments:
        experiment_title = item['id'] + '_' + item['source'] + '_' + item['target']
        if os.path.isfile('../25_11_2018/experiments/' + experiment_title + '/' + experiment_title + '.json'):
            with open('../25_11_2018/experiments/' + experiment_title + '/' + experiment_title + '.json', 'r') as fp:
                results = json.load(fp)
                data['results'][experiment_title] = results
    return data

In [6]:
experiments = [
            {'id': '1', 'source':'imdb', 'target':'uwcse', 'predicate':'workedunder', 'to_predicate':'advisedby'},
            {'id': '2', 'source':'uwcse', 'target':'imdb', 'predicate':'advisedby', 'to_predicate':'workedunder'},
            {'id': '3', 'source':'imdb', 'target':'uwcse', 'predicate':'movie', 'to_predicate':'publication'},
            {'id': '4', 'source':'uwcse', 'target':'imdb', 'predicate':'publication', 'to_predicate':'movie'},
            {'id': '5', 'source':'imdb', 'target':'uwcse', 'predicate':'genre', 'to_predicate':'inphase'},
            {'id': '6', 'source':'uwcse', 'target':'imdb', 'predicate':'inphase', 'to_predicate':'genre'},
            {'id': '7', 'source':'imdb', 'target':'cora', 'predicate':'workedunder', 'to_predicate':'samevenue'},
            {'id': '8', 'source':'imdb', 'target':'cora', 'predicate':'workedunder', 'to_predicate':'samebib'},
            {'id': '9', 'source':'imdb', 'target':'cora', 'predicate':'workedunder', 'to_predicate':'sameauthor'},
            {'id': '10', 'source':'imdb', 'target':'cora', 'predicate':'workedunder', 'to_predicate':'sametitle'},
            {'id': '11', 'source':'uwcse', 'target':'cora', 'predicate':'advisedby', 'to_predicate':'samevenue'},
            {'id': '12', 'source':'uwcse', 'target':'cora', 'predicate':'advisedby', 'to_predicate':'samebib'},
            {'id': '13', 'source':'uwcse', 'target':'cora', 'predicate':'advisedby', 'to_predicate':'sameauthor'},
            {'id': '14', 'source':'uwcse', 'target':'cora', 'predicate':'advisedby', 'to_predicate':'sametitle'},
            {'id': '15', 'source':'yeast', 'target':'twitter', 'predicate':'proteinclass', 'to_predicate':'accounttype'},
            {'id': '16', 'source':'yeast', 'target':'twitter', 'predicate':'interaction', 'to_predicate':'follows'},
            {'id': '17', 'source':'yeast', 'target':'twitter', 'predicate':'location', 'to_predicate':'tweets'},
            {'id': '18', 'source':'yeast', 'target':'twitter', 'predicate':'enzyme', 'to_predicate':'tweets'},
            {'id': '19', 'source':'yeast', 'target':'twitter', 'predicate':'function', 'to_predicate':'tweets'},
            {'id': '20', 'source':'yeast', 'target':'twitter', 'predicate':'phenotype', 'to_predicate':'tweets'},
            {'id': '21', 'source':'yeast', 'target':'twitter', 'predicate':'complex', 'to_predicate':'tweets'},
            {'id': '22', 'source':'twitter', 'target':'yeast', 'predicate':'accounttype', 'to_predicate':'proteinclass'},
            {'id': '23', 'source':'twitter', 'target':'yeast', 'predicate':'follows', 'to_predicate':'interaction'},
            {'id': '24', 'source':'twitter', 'target':'yeast', 'predicate':'tweets', 'to_predicate':'location'},
            {'id': '25', 'source':'twitter', 'target':'yeast', 'predicate':'tweets', 'to_predicate':'enzyme'},
            {'id': '26', 'source':'twitter', 'target':'yeast', 'predicate':'tweets', 'to_predicate':'function'},
            {'id': '27', 'source':'twitter', 'target':'yeast', 'predicate':'tweets', 'to_predicate':'phenotype'},
            {'id': '28', 'source':'twitter', 'target':'yeast', 'predicate':'tweets', 'to_predicate':'complex'},
            {'id': '29', 'source':'nell_sports', 'target':'nell_finances', 'predicate':'teamalsoknownas', 'to_predicate':'companyalsoknownas'},
            {'id': '30', 'source':'nell_sports', 'target':'nell_finances', 'predicate':'teamplaysagainstteam', 'to_predicate':'companyalsoknownas'},
            {'id': '31', 'source':'nell_sports', 'target':'nell_finances', 'predicate':'teamplaysagainstteam', 'to_predicate':'acquired'},
            {'id': '32', 'source':'nell_sports', 'target':'nell_finances', 'predicate':'teamplaysagainstteam', 'to_predicate':'bankboughtbank'},
            {'id': '33', 'source':'nell_sports', 'target':'nell_finances', 'predicate':'athleteplayssport', 'to_predicate':'companyceo'},
            {'id': '34', 'source':'nell_sports', 'target':'nell_finances', 'predicate':'athleteplayssport', 'to_predicate':'bankchiefexecutiveceo'},
            {'id': '35', 'source':'nell_sports', 'target':'nell_finances', 'predicate':'athleteplaysforteam', 'to_predicate':'bankchiefexecutiveceo'},
            {'id': '36', 'source':'nell_sports', 'target':'nell_finances', 'predicate':'athleteplaysforteam', 'to_predicate':'companyceo'},
            {'id': '37', 'source':'nell_sports', 'target':'nell_finances', 'predicate':'teamplayssport', 'to_predicate':'companyeconomicsector'},
            {'id': '38', 'source':'nell_finances', 'target':'nell_sports', 'predicate':'companyalsoknownas', 'to_predicate':'teamalsoknownas'},
            {'id': '39', 'source':'nell_finances', 'target':'nell_sports', 'predicate':'companyalsoknownas', 'to_predicate':'teamplaysagainstteam'},
            {'id': '40', 'source':'nell_finances', 'target':'nell_sports', 'predicate':'acquired', 'to_predicate':'teamplaysagainstteam'},
            {'id': '41', 'source':'nell_finances', 'target':'nell_sports', 'predicate':'bankboughtbank', 'to_predicate':'teamplaysagainstteam'},
            {'id': '42', 'source':'nell_finances', 'target':'nell_sports', 'predicate':'companyceo', 'to_predicate':'athleteplayssport'},
            {'id': '43', 'source':'nell_finances', 'target':'nell_sports', 'predicate':'bankchiefexecutiveceo', 'to_predicate':'athleteplayssport'},
            {'id': '44', 'source':'nell_finances', 'target':'nell_sports', 'predicate':'bankchiefexecutiveceo', 'to_predicate':'athleteplaysforteam'},
            {'id': '45', 'source':'nell_finances', 'target':'nell_sports', 'predicate':'companyceo', 'to_predicate':'athleteplaysforteam'},
            {'id': '46', 'source':'nell_finances', 'target':'nell_sports', 'predicate':'companyeconomicsector', 'to_predicate':'teamplayssport'},
            {'id': '47', 'source':'yeast', 'target':'facebook', 'predicate':'interaction', 'to_predicate':'edge'},
            {'id': '48', 'source':'twitter', 'target':'facebook', 'predicate':'follows', 'to_predicate':'edge'},
            {'id': '49', 'source':'imdb', 'target':'facebook', 'predicate':'workedunder', 'to_predicate':'edge'},
            {'id': '50', 'source':'uwcse', 'target':'facebook', 'predicate':'advisedby', 'to_predicate':'edge'},
]

data = load_data(experiments)
data_old = load_data_old(experiments)

for metric in ['AUC ROC', 'AUC PR', 'CLL', 'Recall', 'F1', 'Precision', 'Learning and Revision time', 'Inference time']:
    display(Markdown('# Results for ' + metric))
    table = []
    for j in range(len(experiments)):
        dataset = experiments[j]['id'] + '_' + experiments[j]['source'] + '_' + experiments[j]['target']
        if dataset in data['results']: 
            #for metric in ['AUC ROC', 'AUC PR']:
                #display(Markdown('## ' + metric))
            mapping_time = ''
            if metric == 'Precision':
                scratch = np.array([item['rdn_b']['Precision'][0] for sublist in data_old['results'][str(dataset)] for item in sublist])
                scratch_rdn = np.array([item['rdn']['Precision'][0] for sublist in data_old['results'][str(dataset)] for item in sublist])
                parameter = np.array([item['transfer']['parameter']['Precision'][0] for sublist in data_old['results'][str(dataset)] for item in sublist])
                transfer = np.array([item['transfer']['Precision'][0] for sublist in data_old['results'][str(dataset)] for item in sublist])
                parameter2 = np.array([item['transfer']['parameter']['Precision'][0] for sublist in data['results'][str(dataset)] for item in sublist])
                transfer2 = np.array([item['transfer']['Precision'][0] for sublist in data['results'][str(dataset)] for item in sublist])
            elif metric == 'Learning and Revision time':
                scratch = np.array([item['rdn_b']['Learning time'] for sublist in data_old['results'][str(dataset)] for item in sublist])
                scratch_rdn = np.array([item['rdn']['Learning time'] for sublist in data_old['results'][str(dataset)] for item in sublist])
                parameter = np.array([item['transfer']['parameter']['Learning time'] for sublist in data_old['results'][str(dataset)] for item in sublist])
                transfer = np.array([item['transfer']['Learning time'] for sublist in data_old['results'][str(dataset)] for item in sublist])
                parameter2 = np.array([item['transfer']['parameter']['Learning time'] for sublist in data['results'][str(dataset)] for item in sublist])
                transfer2 = np.array([item['transfer']['Learning time'] for sublist in data['results'][str(dataset)] for item in sublist])
                #mapping = np.array([item['transfer']['Mapping results']['Total time'] for sublist in data['results'][str(dataset)] for item in sublist])
                #mapping_time = ' (%.1f)' % mapping.mean()
            elif metric == 'Inference time':
                scratch = np.array([item['rdn_b']['Inference time'] for sublist in data_old['results'][str(dataset)] for item in sublist])
                scratch_rdn = np.array([item['rdn']['Inference time'] for sublist in data_old['results'][str(dataset)] for item in sublist])
                parameter = np.array([item['transfer']['parameter']['Learning time'] for sublist in data_old['results'][str(dataset)] for item in sublist])
                transfer = np.array([item['transfer']['Inference time'] for sublist in data_old['results'][str(dataset)] for item in sublist])
                parameter2 = np.array([item['transfer']['parameter']['Learning time'] for sublist in data['results'][str(dataset)] for item in sublist])
                transfer2 = np.array([item['transfer']['Inference time'] for sublist in data['results'][str(dataset)] for item in sublist])
            else:
                scratch = np.array([item['rdn_b'][metric] for sublist in data_old['results'][str(dataset)] for item in sublist])
                scratch_rdn = np.array([item['rdn'][metric] for sublist in data_old['results'][str(dataset)] for item in sublist])
                parameter = np.array([item['transfer']['parameter'][metric] for sublist in data_old['results'][str(dataset)] for item in sublist])
                transfer = np.array([item['transfer'][metric] for sublist in data_old['results'][str(dataset)] for item in sublist])
                parameter2 = np.array([item['transfer']['parameter'][metric] for sublist in data['results'][str(dataset)] for item in sublist])
                transfer2 = np.array([item['transfer'][metric] for sublist in data['results'][str(dataset)] for item in sublist])
            table.append([dataset, '%.3f +/- %.3f' % (parameter2.mean(), 2 * parameter2.std()),
            '%.3f +/- %.3f' % (transfer2.mean(), 2 * transfer2.std()),
            '%.3f +/- %.3f' % (parameter.mean(), 2 * parameter.std()),
            '%.3f +/- %.3f' % (transfer.mean(), 2 * transfer.std()),
            '%.3f +/- %.3f' % (scratch.mean(), 2 * scratch.std()),
            '%.3f +/- %.3f' % (scratch_rdn.mean(), 2 * scratch_rdn.std())])
    display(pd.DataFrame(table, columns=['Experiment', 'trRND-B 2', 'trRND-B 2 Ref', 'trRND-B', 'trRND-B Ref', 'RDN-B', 'RDN']))

# Results for AUC ROC

,Experiment,trRND-B 2,trRND-B 2 Ref,trRND-B,trRND-B Ref,RDN-B,RDN
0,1_imdb_uwcse,0.952 +/- 0.012,0.949 +/- 0.025,0.956 +/- 0.007,0.949 +/- 0.024,0.934 +/- 0.072,0.929 +/- 0.064
1,2_uwcse_imdb,1.000 +/- 0.000,1.000 +/- 0.000,0.999 +/- 0.008,0.999 +/- 0.019,0.981 +/- 0.077,0.943 +/- 0.093
2,6_uwcse_imdb,0.907 +/- 0.063,0.907 +/- 0.063,0.907 +/- 0.063,0.907 +/- 0.063,0.827 +/- 0.333,0.827 +/- 0.333
3,7_imdb_cora,0.573 +/- 0.038,0.605 +/- 0.065,0.525 +/- 0.089,0.614 +/- 0.244,0.676 +/- 0.290,0.613 +/- 0.242
4,9_imdb_cora,0.635 +/- 0.056,0.577 +/- 0.152,0.675 +/- 0.063,0.654 +/- 0.183,0.534 +/- 0.176,0.528 +/- 0.311
5,12_uwcse_cora,0.941 +/- 0.031,0.944 +/- 0.018,0.643 +/- 0.377,0.938 +/- 0.019,0.935 +/- 0.008,0.926 +/- 0.031
6,13_uwcse_cora,0.635 +/- 0.056,0.556 +/- 0.160,0.675 +/- 0.063,0.641 +/- 0.194,0.544 +/- 0.181,0.526 +/- 0.317
7,16_yeast_twitter,0.708 +/- 0.059,0.710 +/- 0.054,0.714 +/- 0.044,0.720 +/- 0.036,0.717 +/- 0.042,0.717 +/- 0.042
8,23_twitter_yeast,0.620 +/- 0.100,0.656 +/- 0.041,0.592 +/- 0.095,0.644 +/- 0.067,0.653 +/- 0.050,0.627 +/- 0.062
9,35_nell_sports_nell_finances,0.795 +/- 0.089,0.781 +/- 0.175,0.800 +/- 0.103,0.765 +/- 0.115,0.592 +/- 0.478,0.600 +/- 0.498
10,37_nell_sports_nell_finances,0.915 +/- 0.098,0.912 +/- 0.075,0.798 +/- 0.020,0.822 +/- 0.037,0.729 +/- 0.072,0.625 +/- 0.120
11,46_nell_finances_nell_sports,0.500 +/- 0.000,0.844 +/- 0.045,0.500 +/- 0.000,0.875 +/- 0.041,0.937 +/- 0.021,0.902 +/- 0.034
12,47_yeast_facebook,0.617 +/- 0.072,0.589 +/- 0.060,0.603 +/- 0.114,0.579 +/- 0.070,0.579 +/- 0.075,0.560 +/- 0.099
13,48_twitter_facebook,0.590 +/- 0.088,0.593 +/- 0.070,0.581 +/- 0.155,0.600 +/- 0.075,0.576 +/- 0.072,0.555 +/- 0.082
14,49_imdb_facebook,0.567 +/- 0.077,0.585 +/- 0.071,0.500 +/- 0.024,0.589 +/- 0.080,0.578 +/- 0.074,0.559 +/- 0.108
15,50_uwcse_facebook,0.591 +/- 0.111,0.572 +/- 0.064,0.549 +/- 0.133,0.593 +/- 0.075,0.577 +/- 0.074,0.560 +/- 0.097

# Results for AUC PR

,Experiment,trRND-B 2,trRND-B 2 Ref,trRND-B,trRND-B Ref,RDN-B,RDN
0,1_imdb_uwcse,0.929 +/- 0.036,0.913 +/- 0.043,0.939 +/- 0.015,0.910 +/- 0.044,0.885 +/- 0.119,0.875 +/- 0.107
1,2_uwcse_imdb,1.000 +/- 0.000,1.000 +/- 0.000,0.999 +/- 0.009,0.998 +/- 0.036,0.968 +/- 0.130,0.904 +/- 0.157
2,6_uwcse_imdb,0.845 +/- 0.095,0.845 +/- 0.095,0.845 +/- 0.095,0.845 +/- 0.095,0.779 +/- 0.294,0.779 +/- 0.294
3,7_imdb_cora,0.640 +/- 0.098,0.655 +/- 0.100,0.532 +/- 0.089,0.608 +/- 0.218,0.659 +/- 0.242,0.610 +/- 0.208
4,9_imdb_cora,0.945 +/- 0.005,0.928 +/- 0.045,0.944 +/- 0.008,0.941 +/- 0.042,0.919 +/- 0.042,0.913 +/- 0.081
5,12_uwcse_cora,0.964 +/- 0.016,0.970 +/- 0.015,0.731 +/- 0.296,0.967 +/- 0.013,0.965 +/- 0.013,0.954 +/- 0.047
6,13_uwcse_cora,0.945 +/- 0.005,0.927 +/- 0.040,0.944 +/- 0.008,0.938 +/- 0.051,0.922 +/- 0.043,0.913 +/- 0.083
7,16_yeast_twitter,0.687 +/- 0.058,0.689 +/- 0.053,0.684 +/- 0.039,0.693 +/- 0.029,0.682 +/- 0.045,0.682 +/- 0.046
8,23_twitter_yeast,0.624 +/- 0.063,0.678 +/- 0.041,0.606 +/- 0.087,0.668 +/- 0.068,0.680 +/- 0.035,0.646 +/- 0.054
9,35_nell_sports_nell_finances,0.829 +/- 0.093,0.822 +/- 0.136,0.850 +/- 0.089,0.788 +/- 0.145,0.663 +/- 0.413,0.663 +/- 0.429
10,37_nell_sports_nell_finances,0.923 +/- 0.116,0.920 +/- 0.086,0.783 +/- 0.022,0.815 +/- 0.043,0.751 +/- 0.063,0.649 +/- 0.106
11,46_nell_finances_nell_sports,0.500 +/- 0.000,0.841 +/- 0.037,0.500 +/- 0.000,0.852 +/- 0.051,0.932 +/- 0.031,0.883 +/- 0.074
12,47_yeast_facebook,0.597 +/- 0.050,0.584 +/- 0.049,0.590 +/- 0.088,0.575 +/- 0.062,0.575 +/- 0.066,0.557 +/- 0.081
13,48_twitter_facebook,0.577 +/- 0.075,0.584 +/- 0.062,0.570 +/- 0.107,0.586 +/- 0.059,0.574 +/- 0.060,0.554 +/- 0.067
14,49_imdb_facebook,0.563 +/- 0.079,0.574 +/- 0.062,0.503 +/- 0.027,0.579 +/- 0.066,0.575 +/- 0.063,0.557 +/- 0.085
15,50_uwcse_facebook,0.573 +/- 0.093,0.568 +/- 0.054,0.545 +/- 0.103,0.584 +/- 0.061,0.575 +/- 0.062,0.558 +/- 0.082

# Results for CLL

,Experiment,trRND-B 2,trRND-B 2 Ref,trRND-B,trRND-B Ref,RDN-B,RDN
0,1_imdb_uwcse,-0.234 +/- 0.016,-0.240 +/- 0.046,-0.229 +/- 0.007,-0.241 +/- 0.046,-0.259 +/- 0.096,-0.752 +/- 0.034
1,2_uwcse_imdb,-0.115 +/- 0.024,-0.124 +/- 0.034,-0.124 +/- 0.090,-0.125 +/- 0.040,-0.174 +/- 0.148,-0.718 +/- 0.026
2,6_uwcse_imdb,-0.317 +/- 0.049,-0.308 +/- 0.058,-0.320 +/- 0.051,-0.308 +/- 0.058,-0.458 +/- 0.598,-0.826 +/- 0.234
3,7_imdb_cora,-0.659 +/- 0.029,-0.659 +/- 0.036,-0.690 +/- 0.020,-0.639 +/- 0.190,-0.601 +/- 0.219,-0.928 +/- 0.095
4,9_imdb_cora,-0.281 +/- 0.060,-0.344 +/- 0.168,-0.256 +/- 0.002,-0.313 +/- 0.182,-0.324 +/- 0.118,-1.242 +/- 0.056
5,12_uwcse_cora,-0.356 +/- 0.172,-0.343 +/- 0.155,-0.624 +/- 0.366,-0.355 +/- 0.165,-0.344 +/- 0.146,-0.911 +/- 0.082
6,13_uwcse_cora,-0.282 +/- 0.058,-0.333 +/- 0.141,-0.260 +/- 0.007,-0.304 +/- 0.140,-0.331 +/- 0.137,-1.245 +/- 0.062
7,16_yeast_twitter,-0.628 +/- 0.031,-0.625 +/- 0.041,-0.625 +/- 0.031,-0.618 +/- 0.030,-0.620 +/- 0.038,-0.896 +/- 0.010
8,23_twitter_yeast,-0.663 +/- 0.023,-0.654 +/- 0.021,-0.673 +/- 0.028,-0.658 +/- 0.028,-0.656 +/- 0.026,-0.920 +/- 0.022
9,35_nell_sports_nell_finances,-0.560 +/- 0.061,-0.581 +/- 0.137,-0.542 +/- 0.072,-0.562 +/- 0.092,-0.771 +/- 0.605,-0.904 +/- 0.165
10,37_nell_sports_nell_finances,-0.355 +/- 0.175,-0.362 +/- 0.145,-0.544 +/- 0.016,-0.527 +/- 0.018,-0.603 +/- 0.046,-0.906 +/- 0.031
11,46_nell_finances_nell_sports,-0.695 +/- 0.000,-0.488 +/- 0.027,-0.695 +/- 0.001,-0.471 +/- 0.041,-0.343 +/- 0.039,-0.792 +/- 0.017
12,47_yeast_facebook,-0.685 +/- 0.055,-0.705 +/- 0.049,-0.678 +/- 0.037,-0.705 +/- 0.049,-0.712 +/- 0.054,-0.933 +/- 0.028
13,48_twitter_facebook,-0.704 +/- 0.074,-0.711 +/- 0.084,-0.682 +/- 0.052,-0.690 +/- 0.060,-0.716 +/- 0.055,-0.933 +/- 0.020
14,49_imdb_facebook,-0.694 +/- 0.047,-0.725 +/- 0.107,-0.696 +/- 0.004,-0.704 +/- 0.049,-0.713 +/- 0.051,-0.934 +/- 0.029
15,50_uwcse_facebook,-0.693 +/- 0.054,-0.715 +/- 0.061,-0.686 +/- 0.032,-0.697 +/- 0.045,-0.714 +/- 0.051,-0.931 +/- 0.030

# Results for Recall

,Experiment,trRND-B 2,trRND-B 2 Ref,trRND-B,trRND-B Ref,RDN-B,RDN
0,1_imdb_uwcse,1.000 +/- 0.000,0.992 +/- 0.020,1.000 +/- 0.000,0.992 +/- 0.022,0.981 +/- 0.051,0.000 +/- 0.000
1,2_uwcse_imdb,1.000 +/- 0.000,1.000 +/- 0.000,1.000 +/- 0.000,1.000 +/- 0.000,1.000 +/- 0.000,0.000 +/- 0.000
2,6_uwcse_imdb,1.000 +/- 0.000,1.000 +/- 0.000,1.000 +/- 0.000,1.000 +/- 0.000,0.800 +/- 0.800,0.000 +/- 0.000
3,7_imdb_cora,0.487 +/- 0.800,0.490 +/- 0.741,0.768 +/- 0.769,0.755 +/- 0.702,0.764 +/- 0.684,0.000 +/- 0.000
4,9_imdb_cora,1.000 +/- 0.000,0.977 +/- 0.096,1.000 +/- 0.000,0.974 +/- 0.106,0.969 +/- 0.126,0.000 +/- 0.000
5,12_uwcse_cora,0.887 +/- 0.124,0.894 +/- 0.095,0.752 +/- 0.674,0.893 +/- 0.110,0.896 +/- 0.081,0.000 +/- 0.000
6,13_uwcse_cora,1.000 +/- 0.000,0.975 +/- 0.102,1.000 +/- 0.000,0.970 +/- 0.122,0.966 +/- 0.138,0.000 +/- 0.000
7,16_yeast_twitter,0.513 +/- 0.033,0.513 +/- 0.033,0.577 +/- 0.187,0.513 +/- 0.034,0.514 +/- 0.031,0.000 +/- 0.000
8,23_twitter_yeast,0.454 +/- 0.455,0.452 +/- 0.261,0.313 +/- 0.474,0.435 +/- 0.321,0.465 +/- 0.215,0.000 +/- 0.000
9,35_nell_sports_nell_finances,0.533 +/- 0.212,0.701 +/- 0.327,0.479 +/- 0.210,0.731 +/- 0.216,0.555 +/- 0.310,0.000 +/- 0.000
10,37_nell_sports_nell_finances,0.836 +/- 0.161,0.845 +/- 0.098,0.841 +/- 0.031,0.848 +/- 0.034,0.291 +/- 0.107,0.000 +/- 0.000
11,46_nell_finances_nell_sports,0.000 +/- 0.000,0.643 +/- 0.275,0.000 +/- 0.000,0.833 +/- 0.281,0.902 +/- 0.028,0.000 +/- 0.000
12,47_yeast_facebook,0.474 +/- 0.218,0.389 +/- 0.296,0.362 +/- 0.320,0.387 +/- 0.378,0.374 +/- 0.303,0.000 +/- 0.000
13,48_twitter_facebook,0.442 +/- 0.309,0.421 +/- 0.308,0.376 +/- 0.448,0.389 +/- 0.370,0.383 +/- 0.317,0.000 +/- 0.000
14,49_imdb_facebook,0.497 +/- 0.328,0.384 +/- 0.270,0.015 +/- 0.082,0.417 +/- 0.306,0.379 +/- 0.296,0.000 +/- 0.000
15,50_uwcse_facebook,0.437 +/- 0.321,0.359 +/- 0.262,0.195 +/- 0.346,0.430 +/- 0.317,0.382 +/- 0.289,0.000 +/- 0.000

# Results for F1

,Experiment,trRND-B 2,trRND-B 2 Ref,trRND-B,trRND-B Ref,RDN-B,RDN
0,1_imdb_uwcse,0.942 +/- 0.004,0.941 +/- 0.008,0.942 +/- 0.004,0.941 +/- 0.009,0.929 +/- 0.026,nan +/- nan
1,2_uwcse_imdb,1.000 +/- 0.000,1.000 +/- 0.000,0.999 +/- 0.013,0.999 +/- 0.013,0.949 +/- 0.084,nan +/- nan
2,6_uwcse_imdb,0.915 +/- 0.054,0.915 +/- 0.054,0.915 +/- 0.054,0.915 +/- 0.054,nan +/- nan,nan +/- nan
3,7_imdb_cora,0.438 +/- 0.398,0.461 +/- 0.370,nan +/- nan,0.608 +/- 0.530,0.651 +/- 0.535,nan +/- nan
4,9_imdb_cora,0.964 +/- 0.020,0.952 +/- 0.044,0.971 +/- 0.004,0.958 +/- 0.054,0.948 +/- 0.060,nan +/- nan
5,12_uwcse_cora,0.877 +/- 0.153,0.887 +/- 0.132,nan +/- nan,0.880 +/- 0.150,0.892 +/- 0.116,nan +/- nan
6,13_uwcse_cora,0.964 +/- 0.020,0.951 +/- 0.048,0.971 +/- 0.004,0.956 +/- 0.063,0.946 +/- 0.067,nan +/- nan
7,16_yeast_twitter,0.612 +/- 0.044,0.612 +/- 0.044,0.629 +/- 0.065,0.612 +/- 0.029,0.612 +/- 0.029,nan +/- nan
8,23_twitter_yeast,0.491 +/- 0.402,0.532 +/- 0.174,0.368 +/- 0.429,0.508 +/- 0.245,0.541 +/- 0.145,nan +/- nan
9,35_nell_sports_nell_finances,0.628 +/- 0.168,0.672 +/- 0.155,0.633 +/- 0.163,0.687 +/- 0.122,0.557 +/- 0.296,nan +/- nan
10,37_nell_sports_nell_finances,0.880 +/- 0.138,0.886 +/- 0.099,0.778 +/- 0.015,0.788 +/- 0.025,0.438 +/- 0.129,nan +/- nan
11,46_nell_finances_nell_sports,nan +/- nan,0.706 +/- 0.144,nan +/- nan,0.808 +/- 0.134,0.858 +/- 0.024,nan +/- nan
12,47_yeast_facebook,0.523 +/- 0.112,0.451 +/- 0.175,0.433 +/- 0.300,0.433 +/- 0.289,0.435 +/- 0.196,nan +/- nan
13,48_twitter_facebook,0.495 +/- 0.151,0.476 +/- 0.162,nan +/- nan,0.443 +/- 0.260,0.439 +/- 0.196,nan +/- nan
14,49_imdb_facebook,0.522 +/- 0.127,0.449 +/- 0.161,nan +/- nan,0.470 +/- 0.193,0.439 +/- 0.182,nan +/- nan
15,50_uwcse_facebook,0.483 +/- 0.194,0.427 +/- 0.170,nan +/- nan,0.476 +/- 0.189,0.441 +/- 0.177,nan +/- nan

# Results for Precision

,Experiment,trRND-B 2,trRND-B 2 Ref,trRND-B,trRND-B Ref,RDN-B,RDN
0,1_imdb_uwcse,0.889 +/- 0.008,0.895 +/- 0.014,0.889 +/- 0.008,0.895 +/- 0.014,0.883 +/- 0.053,nan +/- nan
1,2_uwcse_imdb,1.000 +/- 0.000,1.000 +/- 0.000,0.998 +/- 0.025,0.998 +/- 0.024,0.905 +/- 0.155,nan +/- nan
2,6_uwcse_imdb,0.845 +/- 0.095,0.845 +/- 0.095,0.845 +/- 0.095,0.845 +/- 0.095,nan +/- nan,nan +/- nan
3,7_imdb_cora,0.810 +/- 0.467,0.770 +/- 0.388,nan +/- nan,0.614 +/- 0.226,0.676 +/- 0.252,nan +/- nan
4,9_imdb_cora,0.930 +/- 0.036,0.930 +/- 0.035,0.944 +/- 0.008,0.944 +/- 0.008,0.929 +/- 0.035,nan +/- nan
5,12_uwcse_cora,0.897 +/- 0.332,0.901 +/- 0.288,nan +/- nan,0.896 +/- 0.319,0.904 +/- 0.258,nan +/- nan
6,13_uwcse_cora,0.930 +/- 0.036,0.930 +/- 0.035,0.944 +/- 0.008,0.944 +/- 0.008,0.929 +/- 0.035,nan +/- nan
7,16_yeast_twitter,0.757 +/- 0.064,0.757 +/- 0.064,0.711 +/- 0.113,0.759 +/- 0.015,0.755 +/- 0.023,nan +/- nan
8,23_twitter_yeast,0.726 +/- 0.275,0.700 +/- 0.103,0.740 +/- 0.268,0.696 +/- 0.118,0.673 +/- 0.048,nan +/- nan
9,35_nell_sports_nell_finances,0.808 +/- 0.295,0.689 +/- 0.286,0.981 +/- 0.143,0.655 +/- 0.090,0.565 +/- 0.305,nan +/- nan
10,37_nell_sports_nell_finances,0.934 +/- 0.140,0.934 +/- 0.129,0.724 +/- 0.029,0.736 +/- 0.039,0.911 +/- 0.058,nan +/- nan
11,46_nell_finances_nell_sports,nan +/- nan,0.808 +/- 0.085,nan +/- nan,0.798 +/- 0.033,0.820 +/- 0.058,nan +/- nan
12,47_yeast_facebook,0.612 +/- 0.097,0.597 +/- 0.099,0.612 +/- 0.108,0.589 +/- 0.101,0.588 +/- 0.107,nan +/- nan
13,48_twitter_facebook,0.616 +/- 0.118,0.603 +/- 0.109,nan +/- nan,0.604 +/- 0.106,0.586 +/- 0.111,nan +/- nan
14,49_imdb_facebook,0.610 +/- 0.143,0.594 +/- 0.096,nan +/- nan,0.589 +/- 0.091,0.587 +/- 0.108,nan +/- nan
15,50_uwcse_facebook,0.592 +/- 0.119,0.581 +/- 0.080,nan +/- nan,0.590 +/- 0.093,0.585 +/- 0.107,nan +/- nan

# Results for Learning and Revision time

,Experiment,trRND-B 2,trRND-B 2 Ref,trRND-B,trRND-B Ref,RDN-B,RDN
0,1_imdb_uwcse,1.045 +/- 0.553,4.839 +/- 3.938,7.537 +/- 5.781,17.370 +/- 15.812,11.546 +/- 10.905,3.317 +/- 3.813
1,2_uwcse_imdb,1.580 +/- 1.278,3.658 +/- 2.964,4.618 +/- 5.145,9.855 +/- 10.534,5.656 +/- 4.849,2.072 +/- 1.861
2,6_uwcse_imdb,1.323 +/- 0.890,2.341 +/- 1.442,2.869 +/- 2.975,5.487 +/- 5.004,3.072 +/- 3.171,1.175 +/- 1.069
3,7_imdb_cora,2.500 +/- 1.133,44.169 +/- 27.149,105.640 +/- 158.490,270.619 +/- 386.248,233.646 +/- 213.187,28.745 +/- 36.801
4,9_imdb_cora,1.668 +/- 1.068,7.959 +/- 4.118,8.527 +/- 5.479,25.671 +/- 16.660,17.619 +/- 11.399,5.363 +/- 3.513
5,12_uwcse_cora,28.777 +/- 18.499,285.055 +/- 331.587,222.235 +/- 193.629,741.002 +/- 714.923,332.257 +/- 359.021,34.996 +/- 35.649
6,13_uwcse_cora,6.016 +/- 19.069,24.579 +/- 58.737,10.065 +/- 5.924,52.766 +/- 218.775,16.249 +/- 9.304,4.985 +/- 3.194
7,16_yeast_twitter,3.661 +/- 1.138,13.501 +/- 5.835,38.872 +/- 20.099,89.135 +/- 39.874,60.450 +/- 26.518,10.338 +/- 4.659
8,23_twitter_yeast,5.569 +/- 3.808,26.282 +/- 19.985,43.094 +/- 33.418,100.468 +/- 81.815,83.410 +/- 70.721,16.757 +/- 12.615
9,35_nell_sports_nell_finances,1.595 +/- 0.509,3.682 +/- 1.257,8.213 +/- 16.994,16.436 +/- 19.582,8.705 +/- 4.964,3.293 +/- 1.729
10,37_nell_sports_nell_finances,9.604 +/- 2.625,26.621 +/- 12.011,76.005 +/- 346.979,124.453 +/- 370.770,40.423 +/- 74.643,14.030 +/- 26.829
11,46_nell_finances_nell_sports,2.510 +/- 1.042,327.808 +/- 688.689,304.750 +/- 227.124,985.093 +/- 712.453,715.041 +/- 351.785,114.306 +/- 100.817
12,47_yeast_facebook,15.852 +/- 22.150,74.163 +/- 110.644,110.275 +/- 199.302,264.286 +/- 435.628,196.462 +/- 341.250,37.708 +/- 62.487
13,48_twitter_facebook,10.430 +/- 13.581,41.462 +/- 59.644,98.156 +/- 173.742,227.177 +/- 404.346,190.316 +/- 333.120,36.053 +/- 59.104
14,49_imdb_facebook,6.123 +/- 8.666,59.682 +/- 86.774,99.208 +/- 189.964,273.683 +/- 478.983,186.284 +/- 322.802,37.492 +/- 62.095
15,50_uwcse_facebook,11.127 +/- 16.394,88.428 +/- 159.441,169.410 +/- 637.146,369.011 +/- 1088.069,185.185 +/- 312.827,34.001 +/- 53.089

# Results for Inference time

,Experiment,trRND-B 2,trRND-B 2 Ref,trRND-B,trRND-B Ref,RDN-B,RDN
0,1_imdb_uwcse,1.045 +/- 0.553,0.922 +/- 0.464,7.537 +/- 5.781,1.494 +/- 1.166,1.483 +/- 1.124,1.209 +/- 0.970
1,2_uwcse_imdb,1.580 +/- 1.278,1.236 +/- 0.693,4.618 +/- 5.145,1.956 +/- 1.406,1.559 +/- 1.228,1.195 +/- 0.927
2,6_uwcse_imdb,1.323 +/- 0.890,0.550 +/- 0.139,2.869 +/- 2.975,1.205 +/- 1.174,1.085 +/- 1.292,0.960 +/- 0.791
3,7_imdb_cora,2.500 +/- 1.133,7.483 +/- 8.784,105.640 +/- 158.490,36.673 +/- 101.325,26.458 +/- 44.845,6.714 +/- 10.310
4,9_imdb_cora,1.668 +/- 1.068,2.815 +/- 2.001,8.527 +/- 5.479,11.385 +/- 27.892,4.839 +/- 3.315,3.297 +/- 1.996
5,12_uwcse_cora,28.777 +/- 18.499,103.713 +/- 165.121,222.235 +/- 193.629,138.845 +/- 213.098,8.574 +/- 5.599,6.045 +/- 4.366
6,13_uwcse_cora,6.016 +/- 19.069,86.998 +/- 236.811,10.065 +/- 5.924,100.395 +/- 217.142,4.460 +/- 3.065,3.229 +/- 2.651
7,16_yeast_twitter,3.661 +/- 1.138,1.617 +/- 0.416,38.872 +/- 20.099,3.961 +/- 5.010,2.540 +/- 1.412,1.831 +/- 1.511
8,23_twitter_yeast,5.569 +/- 3.808,2.880 +/- 0.657,43.094 +/- 33.418,4.827 +/- 2.447,4.989 +/- 2.720,3.612 +/- 2.037
9,35_nell_sports_nell_finances,1.595 +/- 0.509,0.895 +/- 0.255,8.213 +/- 16.994,2.035 +/- 1.166,1.928 +/- 1.132,1.689 +/- 0.853
10,37_nell_sports_nell_finances,9.604 +/- 2.625,3.409 +/- 3.132,76.005 +/- 346.979,5.852 +/- 2.696,3.820 +/- 1.665,2.642 +/- 1.410
11,46_nell_finances_nell_sports,2.510 +/- 1.042,30.951 +/- 70.096,304.750 +/- 227.124,13.503 +/- 36.987,9.189 +/- 3.196,3.994 +/- 1.808
12,47_yeast_facebook,15.852 +/- 22.150,4.583 +/- 1.530,110.275 +/- 199.302,8.176 +/- 6.002,7.835 +/- 5.453,5.366 +/- 4.456
13,48_twitter_facebook,10.430 +/- 13.581,4.786 +/- 1.483,98.156 +/- 173.742,8.125 +/- 6.602,7.787 +/- 5.166,4.963 +/- 3.939
14,49_imdb_facebook,6.123 +/- 8.666,4.610 +/- 1.566,99.208 +/- 189.964,8.175 +/- 5.654,7.880 +/- 6.983,5.089 +/- 4.115
15,50_uwcse_facebook,11.127 +/- 16.394,20.111 +/- 50.447,169.410 +/- 637.146,205.632 +/- 1425.217,7.269 +/- 3.149,4.679 +/- 2.640

In [3]:
for j in range(len(experiments)):
    dataset = experiments[j]['id'] + '_' + experiments[j]['source'] + '_' + experiments[j]['target']
    if dataset in data['results']: 
        display(Markdown('# Results for ' + dataset))
    table = []
    for metric in ['AUC ROC', 'AUC PR', 'CLL', 'Recall', 'F1', 'Precision', 'Learning and Revision time', 'Inference time']:
    #for metric in ['AUC ROC', 'AUC PR']:
        if dataset in data['results']: 
            #for metric in ['AUC ROC', 'AUC PR']:
            display(Markdown('## ' + metric))
            if metric == 'Precision':
                for m in range(len(data['results'][str(dataset)])):
                    print('Experiment %s' % (m+1))
                    sc = [item['rdn_b']['Precision'][0] for item in data['results'][str(dataset)][m]]
                    sc_rdn = [item['rdn']['Precision'][0] for item in data['results'][str(dataset)][m]]
                    pr = [item['transfer']['parameter']['Precision'][0] for item in data['results'][str(dataset)][m]]
                    tr = [item['transfer']['Precision'][0] for item in data['results'][str(dataset)][m]] 
                    print('Scratch: %s' % sc)
                    print('Transfer: %s' % pr)
                    print('Transfer & Revision: %s' % tr) 
                    print('\n')
                #scratch = np.array([item['scratch']['Precision'][0] for sublist in data['results'][str(dataset)] for item in sublist])
                #parameter = np.array([item['transfer']['Parameter Learning results']['Precision'][0] for sublist in data['results'][str(dataset)] for item in sublist])
                #transfer = np.array([item['transfer']['Precision'][0] for sublist in data['results'][str(dataset)] for item in sublist])
            elif metric == 'Learning and Revision time':
                for m in range(len(data['results'][str(dataset)])):
                    print('Experiment %s' % (m+1))
                    sc = [item['rdn_b']['Learning time'] for item in data['results'][str(dataset)][m]]
                    sc_rdn = [item['rdn']['Learning time'] for item in data['results'][str(dataset)][m]]
                    pr = ['%s (%.1f)' % (item['transfer']['parameter']['Learning time'], item['transfer']['Mapping results']['Total time']) for item in data['results'][str(dataset)][m]]
                    tr = ['%s (%.1f)' % (item['transfer']['Learning time'], item['transfer']['Mapping results']['Total time']) for item in data['results'][str(dataset)][m]] 
                    print('Scratch: %s' % sc)
                    print('Transfer: %s' % pr)
                    print('Transfer & Revision: %s' % tr) 
                    print('\n')
                #scratch = np.array([item['scratch']['Learning time'] for sublist in data['results'][str(dataset)] for item in sublist])
                #parameter = np.array([item['transfer']['Parameter Learning results']['Learning time'] for sublist in data['results'][str(dataset)] for item in sublist])
                #transfer = np.array([item['transfer']['Learning time'] for sublist in data['results'][str(dataset)] for item in sublist])
            elif metric == 'Inference time':
                for m in range(len(data['results'][str(dataset)])):
                    print('Experiment %s' % (m+1))
                    sc = [item['rdn_b']['Inference time'] for item in data['results'][str(dataset)][m]]
                    sc_rdn = [item['rdn']['Inference time'] for item in data['results'][str(dataset)][m]]
                    pr = [item['transfer']['parameter']['Inference time'] for item in data['results'][str(dataset)][m]]
                    tr = [item['transfer']['Inference time'] for item in data['results'][str(dataset)][m]] 
                    print('Scratch: %s' % sc)
                    print('Transfer: %s' % pr)
                    print('Transfer & Revision: %s' % tr) 
                    print('\n')
                #scratch = np.array([item['scratch']['Inference time'] for sublist in data['results'][str(dataset)] for item in sublist])
                #parameter = np.array([item['transfer']['Parameter Learning results']['Learning time'] for sublist in data['results'][str(dataset)] for item in sublist])
                #transfer = np.array([item['transfer']['Inference time'] for sublist in data['results'][str(dataset)] for item in sublist])
            else:
                for m in range(len(data['results'][str(dataset)])):
                    print('Experiment %s' % (m+1))
                    sc = [item['rdn_b'][metric] for item in data['results'][str(dataset)][m]]
                    sc_rdn = [item['rdn'][metric] for item in data['results'][str(dataset)][m]]
                    pr = [item['transfer']['parameter'][metric] for item in data['results'][str(dataset)][m]]
                    tr = [item['transfer'][metric] for item in data['results'][str(dataset)][m]] 
                    pvalue_table = []
                    pvalue = stats.ttest_rel(tr,sc)
                    pvalue2 = stats.ttest_rel(tr,sc_rdn)
                    #print(pvalue)
                    pvalue_table.append(['transferRDN-B Ref', '%.3f' % (pvalue[1]), '%.3f' % (pvalue2[1])])
                    pvalue = stats.ttest_rel(pr, sc)
                    pvalue2 = stats.ttest_rel(pr, sc_rdn)
                    #print(pvalue)
                    pvalue_table.append(['transferRDN-B', '%.3f' % (pvalue[1]), '%.3f' % (pvalue2[1])])
                    display(pd.DataFrame(pvalue_table, columns=['p-value', 'RDN-B', 'RDN']))
                    print('Scratch RDN-B: %s' % sc)
                    print('Scratch RDN: %s' % sc_rdn)
                    print('Transfer: %s' % pr)
                    print('Transfer & Revision: %s' % tr) 
                    print('\n')
                #scratch = np.array([item['scratch'][metric] for sublist in data['results'][str(dataset)] for item in sublist])
                #parameter = np.array([item['transfer']['Parameter Learning results'][metric] for sublist in data['results'][str(dataset)] for item in sublist])
                #transfer = np.array([item['transfer'][metric] for sublist in data['results'][str(dataset)] for item in sublist])
            #print('\n')
            #print('Scratch: %s' % scratch)
            #print('Transfer: %s' % parameter)
            #print('Transfer & Revision: %s' % transfer)

# Results for 1_imdb_uwcse

## AUC ROC

Experiment 1

KeyError: 'rdn_b'